#!/bin/bash
# code from /etc/init.d/faspbuffers

echo 'Write buffer max' `cat /proc/sys/net/core/wmem_max`
echo 24000000 > /proc/sys/net/core/wmem_max
echo 'Write buffer max changed to' `cat /proc/sys/net/core/wmem_max`

echo 'Read buffer max' `cat /proc/sys/net/core/rmem_max`
echo 24000000 > /proc/sys/net/core/rmem_max
echo 'Read buffer max changed to' `cat /proc/sys/net/core/rmem_max`
